//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWindowsClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISamples")]
    public interface ISamples {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamples/GetSecretCode", ReplyAction="http://tempuri.org/ISamples/GetSecretCodeResponse")]
        string GetSecretCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamples/GetSecretCode", ReplyAction="http://tempuri.org/ISamples/GetSecretCodeResponse")]
        System.Threading.Tasks.Task<string> GetSecretCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamples/GetMemberCode", ReplyAction="http://tempuri.org/ISamples/GetMemberCodeResponse")]
        string GetMemberCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamples/GetMemberCode", ReplyAction="http://tempuri.org/ISamples/GetMemberCodeResponse")]
        System.Threading.Tasks.Task<string> GetMemberCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamples/GetPublicCode", ReplyAction="http://tempuri.org/ISamples/GetPublicCodeResponse")]
        string GetPublicCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamples/GetPublicCode", ReplyAction="http://tempuri.org/ISamples/GetPublicCodeResponse")]
        System.Threading.Tasks.Task<string> GetPublicCodeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISamplesChannel : IntranetWindowsClient.ServiceReference1.ISamples, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SamplesClient : System.ServiceModel.ClientBase<IntranetWindowsClient.ServiceReference1.ISamples>, IntranetWindowsClient.ServiceReference1.ISamples {
        
        public SamplesClient() {
        }
        
        public SamplesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SamplesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SamplesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SamplesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetSecretCode() {
            return base.Channel.GetSecretCode();
        }
        
        public System.Threading.Tasks.Task<string> GetSecretCodeAsync() {
            return base.Channel.GetSecretCodeAsync();
        }
        
        public string GetMemberCode() {
            return base.Channel.GetMemberCode();
        }
        
        public System.Threading.Tasks.Task<string> GetMemberCodeAsync() {
            return base.Channel.GetMemberCodeAsync();
        }
        
        public string GetPublicCode() {
            return base.Channel.GetPublicCode();
        }
        
        public System.Threading.Tasks.Task<string> GetPublicCodeAsync() {
            return base.Channel.GetPublicCodeAsync();
        }
    }
}
