//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EssentialWCFClient.EssentialWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EssentialWCF.IStockQuoteService")]
    public interface IStockQuoteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockQuoteService/GetQuote", ReplyAction="http://tempuri.org/IStockQuoteService/GetQuoteResponse")]
        double GetQuote(string symbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockQuoteService/GetQuote", ReplyAction="http://tempuri.org/IStockQuoteService/GetQuoteResponse")]
        System.Threading.Tasks.Task<double> GetQuoteAsync(string symbol);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockQuoteServiceChannel : EssentialWCFClient.EssentialWCF.IStockQuoteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockQuoteServiceClient : System.ServiceModel.ClientBase<EssentialWCFClient.EssentialWCF.IStockQuoteService>, EssentialWCFClient.EssentialWCF.IStockQuoteService {
        
        public StockQuoteServiceClient() {
        }
        
        public StockQuoteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockQuoteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockQuoteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockQuoteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetQuote(string symbol) {
            return base.Channel.GetQuote(symbol);
        }
        
        public System.Threading.Tasks.Task<double> GetQuoteAsync(string symbol) {
            return base.Channel.GetQuoteAsync(symbol);
        }
    }
}
